---
grub_password_admin: admin
grub_password_passwd: grub.pbkdf2.sha512.10000.6CE338C69BC5180354034EEA28BB34BF6D50993A0AEAAE3F001F7CF8078BC3FBCB7968A4BE641AEB00D822FE55E0739ABF4D5F853AECA77958AC90A3DEC7132A.222738FE51C9A000ED1ECB77FA1A28C64AF1DE58D14F397DBF611343D7DC3443E38240663B8690F26F8F1A30BB58A88CCA9EDC4525F4DA0D93D8F2E7FB4623F0
grub_password_unrestricted: true
grub_password_unrestricted_files:
  - /etc/grub.d/10_linux
  - /etc/grub.d/20_linux_xen
grub_password_mkconfig: /usr/sbin/grub-mkconfig
grub_password_file: /etc/grub.d/40_custom
grub_boot_path: /boot/grub

pkg_cache_seconds: 3600
pkg_daily_package_download: true
base_pkg_daily_package_command: "apt-get update && apt-get --assume-yes --download-only upgrade"
base_pkg_packages:
  [
    "apt-show-versions",
    "bind9utils",
    "build-essential",
    "curl",
    "git",
    "grep",
    "hwinfo",
    "linux-headers-{{ ansible_kernel }}",
    "net-tools",
    "openssl",
    "python3",
    "python3-pip",
    "python3-setuptools",
    "software-properties-common",
    "tar",
    "traceroute",
    "tzdata",
    "vim",
    "wget",
    "whois",
  ]
base_system_timezone: America/New_York
base_system_locale: "en_US.UTF-8"
base_system_language: "en_US.UTF-8"
base_swap_vm_swappiness: 1
base_swap_vm_vfs_cache_pressure: 50
base_swap_vm_hugepages: 20480
base_swap_swapfile_size: "{{ (ansible_memtotal_mb * 1.5) | int }}m"

audit_tools_enabled: true
audit_tools_cache_seconds: 3600
audit_tools_packages: ["aide", "auditd", "debsums", "chkrootkit", "rkhunter"]
audit_tools_cron_frequency: daily
# audit_tools_initalize: false
audit_tools_initalize: true

audit_tools_chkrootkit_rundaily: true
audit_tools_chkrootkit_rundaily_opts: "-q"
audit_tools_chkrootkit_diffmode: false


network_access_enabled: true
network_access_cache_seconds: 3600
network_access_packages:
  ["fail2ban", "sendmail", "ufw", "openssh-client", "openssh-server"]

network_access_ssh_max_sessions: 2

network_access_fail2ban_loglevel: INFO
network_access_fail2ban_logtarget: /var/log/fail2ban.log
network_access_fail2ban_socket: /var/run/fail2ban/fail2ban.sock

network_access_fail2ban_ignoreip: 127.0.0.1/8
network_access_fail2ban_bantime: 600
network_access_fail2ban_maxretry: 6

network_access_fail2ban_backend: polling

network_access_fail2ban_destemail: root@localhost
network_access_fail2ban_banaction: iptables-multiport
network_access_fail2ban_mta: sendmail
network_access_fail2ban_protocol: tcp
network_access_fail2ban_chain: INPUT

network_access_fail2ban_action: action_

network_access_fail2ban_services:
  # SSHD-BASIC will permit any user with an existing account to make a few typos before getting their password right and then move on to my 2FA restrictions and configurations.
  - name: sshd
    port: ssh
    filter: sshd
    logpath: /var/log/auth.log
    maxretry: 10
    # bantime: 600
    bantime: 60

  # SSHD-AGGRESSIVE will promptly ban the source IP.adx of anyone who tries to login with an account that doesn't exist on the system –or is one of the configured trigger accounts. (No one shall login remotely as root, oracle, cisco, etc)
  # - name: sshd-aggressive
  #   port: ssh
  #   mode: aggressive
  #   filter: sshd-aggressive
  #   logpath: /var/log/auth.log
  #   maxretry: 0
  #   bantime: 3888000 # fuck right off for 45 days

  # SSHD-AGGRESSIVE  No one shall login remotely as root, oracle, cisco, etc
  - name: sshd-user-ban
    port: ssh
    filter: sshd-user-ban
    logpath: /var/log/auth.log
    maxretry: 1
    bantime: 60
    # 1 min
    findtime: 120
    # 2 min
    # bantime: 21600
    # # 6 hrs
    # findtime: 3000
    # # 30 mins

  # - name: traefik-auth
  #   port: http,https
  #   filter: traefik-auth
  #   maxretry: 1
  #   logpath: /var/log/traefik/access.log
  # - name: traefik-botsearch
  #   port: http,https
  #   filter: traefik-botsearch
  #   maxretry: 1
  #   logpath: /var/log/traefik/access.log
  # - name: traefik-badbots
  #   port: http,https
  #   filter: traefik-badbots
  #   maxretry: 1
  #   logpath: /var/log/traefik/access.log

network_access_fail2ban_instant_block:
  - adm
  - admin
  - administrator
  - ansible
  - apache
  - at
  - azureuser
  - backup
  - bb
  - bin
  - cron
  - daemon
  - db2fenc1
  - db2inst1
  - Debian-exim
  - ec2-user
  - ftp
  - games
  - gdm
  - gnats
  - guest
  - halt
  - info
  - irc
  - list
  - lp
  - mail
  - man
  - mysql
  - named
  - news
  - nobody
  - ntp
  - operator
  - oracle
  - oracle8
  - pi
  - portage
  - postfix
  - postgres
  - postmaster
  - proxy
  - public
  - puppet
  - root
  - rpc
  - rwhod
  - shutdown
  - smmsp
  - smmta
  - squid
  - sshd
  - sync
  - sys
  - system
  - test
  - toor
  - user
  - uucp
  - websphere
  - www-data
  - vagrant
