---
ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null'

ansible_user: vagrant
ansible_ssh_pass: vagrant
ansible_sudo_pass: vagrant

created_user_name: placeholder_overriden_in_vault.yml
created_user_password: placeholder_overriden_in_vault.yml
created_user_password_salt: placeholder_overriden_in_vault.yml
created_user_ssh_pubkey: placeholder_overriden_in_vault.yml
