---
hosts:
  children:
    ubuntu:
      hosts:
        ubuntu-focal:
      vars:
        ansible_port: 2222
        ansible_host: 127.0.0.1

    # system76-popos:
    #   hosts:
    #     system76-popos:
    #   vars:
    #     ansible_port: 2200
    #     ansible_host: 127.0.0.1
    #     docker_apt_gpg_key: https://download.docker.com/linux/ubuntu/gpg
    #     docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
