---
blank_issues_enabled: false

contact_links:
  - name: Get help on Discord
    url: https://discord.gg/F6pR93n
    about: Have a question? Not sure if your issue affects everyone reproducibly? The quickest way to get help is on the k8s@home Discord!
