---
packages:
  - git-core
  - zlib
  - zlib-devel
  - gcc-c++
  - patch
  - readline
  - readline-devel
  - libffi-devel
  - openssl-devel
  - make
  - bzip2
  - autoconf
  - automake
  - libtool
  - bison
  - curl
  - sqlite-devel
  - jq
  - python3
