---
# role: base_tools
# file: tasks/tasks.yml

- name: "package : ensure that repositories are up to date"
  apt:
    update_cache: true
    cache_valid_time: "{{ base_cache_seconds }}"

- name: "package : ensure the system can use the https transport for apt"
  package:
    name: "apt-transport-https"
    state: present
  register: https_package_res
  retries: 30
  until: https_package_res is success

- name: "package : install packages for base"
  package:
    name: "{{ base_packages }}"
    state: present
  register: base_package_res
  retries: 10
  until: base_package_res is success

- name: "package : create daily cron to download latest"
  cron:
    name: "Download packages"
    special_time: daily
    job: "sleep $(( ( RANDOM % 300 )  + 1 )) && {{ base_daily_package_command }}"
  when: "{{ base_daily_package_download }}|bool == True"

- name: "os : generate en_US.UTF-8 locale"
  locale_gen:
    name: "{{ base_system_locale }}"
    state: present
  notify:
    - rebuild locales database

- name: "os : Ensure localisation files for '{{ base_system_locale }}' are available"
  locale_gen:
    name: "{{ base_system_locale }}"
    state: present

- name: "os : Ensure localisation files for '{{ base_system_language }}' are available"
  locale_gen:
    name: "{{ base_system_language }}"
    state: present

- name: "os : Get current locale and language configuration"
  command: localectl status
  register: locale_status
  changed_when: false

- name: "os : Parse LANG from current locale and language configuration"
  set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: "os : Parse LANGUAGE from current locale and language configuration"
  set_fact:
    locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

- name: "os : Configure locale to '{{ base_system_locale }}' and language to '{{ base_system_language }}'"
  command: localectl set-locale LANG={{ base_system_locale }} LANGUAGE={{ base_system_language }}
  changed_when: locale_lang != base_system_locale or locale_language != base_system_language

- name: "os : set timezone to {{ base_timezone }}"
  timezone:
    name: "{{ base_timezone }}"

- name: "os : copy dotfiles to root"
  copy:
    src: dotfiles/
    dest: /root/
    owner: root
    group: root
    mode: "0755"

- name: "os : copy dotfiles to skel"
  copy:
    src: dotfiles/
    dest: /etc/skel/
    owner: root
    group: root
    mode: "0755"

- name: "os : set correct umask on /etc/bashrc"
  lineinfile:
    create: true
    path: /etc/bashrc
    regexp: '(^\s+umask) (002|022)'
    line: '\1 027'

- name: "os : set correct umask on /etc/profile"
  lineinfile:
    create: true
    path: /etc/profile
    regexp: '(^\s+umask) (002|022)'
    line: '\1 027'

- name: "os : set profile on host"
  blockinfile:
    dest: "/etc/profile"
    insertafter: EOF
    block: |
      . /etc/os-release

- name: "swap : set swappiness"
  sysctl:
    name: vm.swappiness
    value: "{{ base_swap_vm_swappiness }}"

- name: "swap : set vm.vfs_cache_pressure"
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ base_swap_vm_vfs_cache_pressure }}"
    state: present
  tags:
    - install
